---
- name: Install and Configure Apache HTTP Server on Amazon Linux 2
  hosts: all
  become: yes
  tasks:
    - name: Install Apache HTTP Server (httpd)
      yum:
        name: httpd
        state: present

    - name: Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Configure httpd to serve a sample index.html
      copy:
        content: "<html><body><h1>Welcome to My Website!</h1></body></html>"
        dest: /var/www/html/index.html
      notify: Restart httpd

  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
