---
- name: Update Amazon Linux 2
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
        update_cache: yes
