---
- name: Install Git, Tree, and Cron on Amazon Linux 2
  hosts: myafrique_inventory
  become: true 
  gather_facts: true 

  tasks:
    - name: Install Git, Tree, and Cron packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - tree
        - cronie  # Cron package for Amazon Linux 2

    - name: Start and enable cron service
      service:
        name: crond
        state: started
        enabled: yes
